version: '3.5'

volumes:
  data:

services:
  database:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=iKIK983J9JsimjMSD9QJRU23NJMIMJosmaojsmjOIo0o9o
    volumes:
      - data:/var/lib/postgresql/data
      - type: tmpfs
        target: /dev/shm
  app:
    container_name: api-rest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - JWT_SECRET=576D5A7134743677397A24432646294A404E635266556A586E32723575387821
      - DATABASE_URL=postgresql://postgres:value@191.101.234.50:5432/postgres
    depends_on:
      - database
    ports:
      - "3333:3333"